### ISSUE TITLE
Would you be open to adding an open source license for this repo?

### ISSUE THREAD

**Issue by jjudd** [coeuvre/bazel-find-non-deterministic-actions#1]
Hi! I think this is a neat repo and I've found it useful. Thanks for creating it. That said, it does not currently have a license associated with it. Would you be willing to license the code under something like Apache 2, MIT, GPL, etc? 

I ask because, I believe without a license the code is copyrighted and thus I can't safely copy, distribute, modify, etc. the code.

**Comment by coeuvre** [comment]
Thanks for reaching out! I have licensed the code under MIT by https://github.com/coeuvre/bazel-find-non-deterministic-actions/commit/2f08c5ffadfbe2ea3f00c3e120e53563641150f1. Feel free to use it any way you want.
